// 大相撲データ
// 注意: サンプルデータです。実際の番付・成績とは差異がある場合があります。
// データは2026年初場所頃の状況を想定しています。

const SITE_META = {
  dataAsOf: '2026年初場所（一月場所）後',
  note: 'このサイトのデータはサンプルです。実際の番付・成績とは異なる場合があります。',
};

const STABLES = [
  {
    id: 'isegahama',
    name: '伊勢ヶ濱部屋',
    nameRomaji: 'Isegahama-beya',
    ichimon: '伊勢ヶ濱一門',
    location: '東京都江東区清澄',
    master: '伊勢ヶ濱親方（元横綱・旭富士）',
    established: '1993年（再興）',
    description: '元横綱・旭富士が興した部屋。横綱・照ノ富士をはじめ、安美錦、宝富士など多くの関取を育てた名門。'
  },
  {
    id: 'tatsunami',
    name: '立浪部屋',
    nameRomaji: 'Tatsunami-beya',
    ichimon: '時津風一門',
    location: '東京都墨田区石原',
    master: '立浪親方（元小結・旭豊）',
    established: '1915年（創設）',
    description: 'モンゴル出身力士を多く受け入れる伝統ある部屋。横綱・豊昇龍を擁する。'
  },
  {
    id: 'nishonoseki',
    name: '二所ノ関部屋',
    nameRomaji: 'Nishonoseki-beya',
    ichimon: '二所ノ関一門',
    location: '茨城県阿見町',
    master: '二所ノ関親方（元横綱・稀勢の里）',
    established: '2021年（独立）',
    description: '元横綱・稀勢の里が独立して設立した部屋。横綱・大の里を育てた新進気鋭の部屋。'
  },
  {
    id: 'sadogatake',
    name: '佐渡ヶ嶽部屋',
    nameRomaji: 'Sadogatake-beya',
    ichimon: '二所ノ関一門',
    location: '千葉県松戸市岩瀬',
    master: '佐渡ヶ嶽親方（元関脇・琴ノ若）',
    established: '1955年',
    description: '「琴」の四股名を継ぐ伝統ある部屋。大関・琴櫻を擁する。'
  },
  {
    id: 'tagonoura',
    name: '田子ノ浦部屋',
    nameRomaji: 'Tagonoura-beya',
    ichimon: '二所ノ関一門',
    location: '東京都江戸川区松島',
    master: '田子ノ浦親方（元前頭・隆の鶴）',
    established: '2012年',
    description: '元横綱・稀勢の里、関脇・高安を輩出した部屋。'
  },
  {
    id: 'hakkaku',
    name: '八角部屋',
    nameRomaji: 'Hakkaku-beya',
    ichimon: '高砂一門',
    location: '東京都墨田区亀沢',
    master: '八角親方（元横綱・北勝海）',
    established: '1993年',
    description: '日本相撲協会理事長を務める八角親方の部屋。'
  },
  {
    id: 'takasago',
    name: '高砂部屋',
    nameRomaji: 'Takasago-beya',
    ichimon: '高砂一門',
    location: '東京都墨田区本所',
    master: '高砂親方（元関脇・朝赤龍）',
    established: '1878年',
    description: '相撲界最古級の部屋のひとつ。元横綱・朝青龍を輩出。朝乃山が看板力士。'
  },
  {
    id: 'kokonoe',
    name: '九重部屋',
    nameRomaji: 'Kokonoe-beya',
    ichimon: '高砂一門',
    location: '東京都墨田区石原',
    master: '九重親方（元大関・千代大海）',
    established: '1967年',
    description: '元横綱・千代の富士、千代の山らを輩出した名門。'
  },
  {
    id: 'dewanoumi',
    name: '出羽海部屋',
    nameRomaji: 'Dewanoumi-beya',
    ichimon: '出羽海一門',
    location: '東京都墨田区両国',
    master: '出羽海親方（元前頭・小城ノ花）',
    established: '江戸時代',
    description: '相撲界最古の部屋の一つ。多くの横綱を輩出した名門中の名門。'
  },
  {
    id: 'kasugano',
    name: '春日野部屋',
    nameRomaji: 'Kasugano-beya',
    ichimon: '出羽海一門',
    location: '東京都墨田区両国',
    master: '春日野親方（元関脇・栃乃和歌）',
    established: '江戸時代',
    description: '栃錦、栃ノ海など歴代横綱を輩出。栃ノ心、栃煌山を擁した名門。'
  },
  {
    id: 'oitekaze',
    name: '追手風部屋',
    nameRomaji: 'Oitekaze-beya',
    ichimon: '伊勢ヶ濱一門',
    location: '埼玉県草加市瀬崎',
    master: '追手風親方（元前頭・大翔山）',
    established: '1998年',
    description: '関取多数を抱える大所帯。大栄翔、遠藤、翔猿らが所属。'
  },
  {
    id: 'shikoroyama',
    name: '錣山部屋',
    nameRomaji: 'Shikoroyama-beya',
    ichimon: '時津風一門',
    location: '東京都江戸川区北小岩',
    master: '錣山親方（元関脇・寺尾）',
    established: '2004年',
    description: '元寺尾が興した部屋。阿炎が看板力士。'
  },
  {
    id: 'arashio',
    name: '荒汐部屋',
    nameRomaji: 'Arashio-beya',
    ichimon: '時津風一門',
    location: '東京都中央区日本橋浜町',
    master: '荒汐親方（元前頭・大豊）',
    established: '2002年',
    description: '都心に位置する部屋。若隆景、若元春の兄弟力士を擁する。'
  },
  {
    id: 'tokitsukaze',
    name: '時津風部屋',
    nameRomaji: 'Tokitsukaze-beya',
    ichimon: '時津風一門',
    location: '東京都墨田区両国',
    master: '時津風親方（元前頭・時津海）',
    established: '1769年',
    description: '時津風一門の総本山。豊山、双葉山ゆかりの伝統ある部屋。'
  },
  {
    id: 'sakaigawa',
    name: '境川部屋',
    nameRomaji: 'Sakaigawa-beya',
    ichimon: '出羽海一門',
    location: '東京都江戸川区西小岩',
    master: '境川親方（元小結・両国）',
    established: '1998年',
    description: '妙義龍、佐田の海、平戸海など多くの関取を育てる。'
  },
  {
    id: 'kise',
    name: '木瀬部屋',
    nameRomaji: 'Kise-beya',
    ichimon: '時津風一門',
    location: '東京都墨田区東駒形',
    master: '木瀬親方（元前頭・肥後ノ海）',
    established: '1996年',
    description: '宇良、志摩ノ海、英乃海など個性派力士を多く抱える。'
  },
  {
    id: 'otowayama',
    name: '音羽山部屋',
    nameRomaji: 'Otowayama-beya',
    ichimon: '二所ノ関一門',
    location: '東京都墨田区本所',
    master: '音羽山親方（元大関・霧島／旧大関・陸奥嵐の系譜）',
    established: '2023年',
    description: '元大関・霧島が独立して設立した新部屋。'
  },
  {
    id: 'futagoyama',
    name: '二子山部屋',
    nameRomaji: 'Futagoyama-beya',
    ichimon: '二所ノ関一門',
    location: '東京都台東区東浅草',
    master: '二子山親方（元大関・雅山）',
    established: '2013年',
    description: '元大関・雅山が興した部屋。'
  },
  {
    id: 'takadagawa',
    name: '高田川部屋',
    nameRomaji: 'Takadagawa-beya',
    ichimon: '二所ノ関一門',
    location: '東京都台東区東浅草',
    master: '高田川親方（元関脇・安芸乃島）',
    established: '1994年',
    description: '輝、白鷹山などを抱える。'
  },
  {
    id: 'asakayama',
    name: '浅香山部屋',
    nameRomaji: 'Asakayama-beya',
    ichimon: '伊勢ヶ濱一門',
    location: '大阪府堺市北区',
    master: '浅香山親方（元大関・魁皇）',
    established: '2014年',
    description: '元大関・魁皇が興した部屋。大阪に拠点を置く。'
  },
];

const RIKISHI = [
  // ===== 横綱 =====
  {
    id: 'hoshoryu',
    name: '豊昇龍',
    nameKana: 'ほうしょうりゅう',
    nameRomaji: 'Hoshoryu Tomokatsu',
    realName: 'スガラグチャー・バイバヤル',
    rank: '横綱',
    rankNum: 1,
    side: '東',
    stableId: 'tatsunami',
    birthplace: 'モンゴル・ウランバートル',
    birthplaceCountry: 'モンゴル',
    birthdate: '1999-05-22',
    height: 187,
    weight: 145,
    debut: '2018年1月',
    debutRank: '前相撲',
    yusho: 3,
    sansho: { shukunsho: 1, kantosho: 3, ginosho: 2 },
    kinboshi: 1,
    favoriteKimarite: ['右四つ', '投げ技', '内無双'],
    profile: '元横綱・朝青龍の甥。技巧派で「平成の朝青龍」と呼ばれる。2025年初場所後に第74代横綱に昇進。'
  },
  {
    id: 'onosato',
    name: '大の里',
    nameKana: 'おおのさと',
    nameRomaji: 'Onosato Daiki',
    realName: '中村大輝',
    rank: '横綱',
    rankNum: 1,
    side: '西',
    stableId: 'nishonoseki',
    birthplace: '石川県津幡町',
    birthplaceCountry: '日本',
    birthdate: '2000-06-07',
    height: 192,
    weight: 182,
    debut: '2023年5月',
    debutRank: '幕下10枚目格付出',
    yusho: 4,
    sansho: { shukunsho: 2, kantosho: 2, ginosho: 2 },
    kinboshi: 0,
    favoriteKimarite: ['突き押し', '寄り切り'],
    profile: '日本大学から幕下付出デビュー。スピード出世で2025年初場所後に第75代横綱に昇進。日本人横綱の誕生で大きな話題に。'
  },

  // ===== 大関 =====
  {
    id: 'kotozakura',
    name: '琴櫻',
    nameKana: 'ことざくら',
    nameRomaji: 'Kotozakura Masakatsu',
    realName: '鎌谷将且',
    rank: '大関',
    rankNum: 2,
    side: '東',
    stableId: 'sadogatake',
    birthplace: '千葉県松戸市',
    birthplaceCountry: '日本',
    birthdate: '1997-11-19',
    height: 188,
    weight: 175,
    debut: '2015年11月',
    debutRank: '前相撲',
    yusho: 1,
    sansho: { shukunsho: 2, kantosho: 1, ginosho: 1 },
    kinboshi: 0,
    favoriteKimarite: ['右四つ', '寄り切り', '上手投げ'],
    profile: '元大関・琴櫻（先代）の孫。2024年に四股名を「琴ノ若」から「琴櫻」に改名し、同年九州場所で初優勝。'
  },
  {
    id: 'kirishima',
    name: '霧島',
    nameKana: 'きりしま',
    nameRomaji: 'Kirishima Tetsuo',
    realName: 'バヤンジャルガル',
    rank: '関脇',
    rankNum: 3,
    side: '東',
    stableId: 'otowayama',
    birthplace: 'モンゴル・ウランバートル',
    birthplaceCountry: 'モンゴル',
    birthdate: '1996-04-24',
    height: 187,
    weight: 145,
    debut: '2015年3月',
    debutRank: '前相撲',
    yusho: 2,
    sansho: { shukunsho: 3, kantosho: 2, ginosho: 3 },
    kinboshi: 2,
    favoriteKimarite: ['右四つ', '上手投げ', '寄り切り'],
    profile: '元大関。投げ技を得意とする技巧派。2024年に師匠の引退に伴い陸奥部屋から音羽山部屋へ移籍。'
  },

  // ===== 関脇 =====
  {
    id: 'wakamotoharu',
    name: '若元春',
    nameKana: 'わかもとはる',
    nameRomaji: 'Wakamotoharu Atsushi',
    realName: '大波港',
    rank: '関脇',
    rankNum: 3,
    side: '西',
    stableId: 'arashio',
    birthplace: '福島県福島市',
    birthplaceCountry: '日本',
    birthdate: '1993-10-05',
    height: 187,
    weight: 145,
    debut: '2011年11月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 1 },
    kinboshi: 0,
    favoriteKimarite: ['左四つ', '寄り切り', '上手投げ'],
    profile: '若隆景の実兄。三兄弟力士の次男。粘り強い左四つの相撲が持ち味。'
  },
  {
    id: 'daieisho',
    name: '大栄翔',
    nameKana: 'だいえいしょう',
    nameRomaji: 'Daieisho Hayato',
    realName: '高橋勇人',
    rank: '関脇',
    rankNum: 3,
    side: '東',
    stableId: 'oitekaze',
    birthplace: '埼玉県朝霞市',
    birthplaceCountry: '日本',
    birthdate: '1993-11-10',
    height: 182,
    weight: 162,
    debut: '2012年1月',
    debutRank: '前相撲',
    yusho: 1,
    sansho: { shukunsho: 3, kantosho: 1, ginosho: 4 },
    kinboshi: 4,
    favoriteKimarite: ['突き押し', '押し出し', 'はたき込み'],
    profile: '埼玉栄高校出身。鋭い突き押しで上位陣を苦しめる。2021年初場所で初優勝。'
  },

  // ===== 小結 =====
  {
    id: 'abi',
    name: '阿炎',
    nameKana: 'あび',
    nameRomaji: 'Abi Masatora',
    realName: '堀切川政虎',
    rank: '小結',
    rankNum: 4,
    side: '東',
    stableId: 'shikoroyama',
    birthplace: '埼玉県越谷市',
    birthplaceCountry: '日本',
    birthdate: '1994-05-04',
    height: 192,
    weight: 152,
    debut: '2013年5月',
    debutRank: '前相撲',
    yusho: 1,
    sansho: { shukunsho: 2, kantosho: 2, ginosho: 1 },
    kinboshi: 2,
    favoriteKimarite: ['突き押し', '突き出し', 'はたき込み'],
    profile: '長身を活かした突っ張りが武器。2022年九州場所で初優勝。'
  },
  {
    id: 'wakatakakage',
    name: '若隆景',
    nameKana: 'わかたかかげ',
    nameRomaji: 'Wakatakakage Atsushi',
    realName: '大波渥',
    rank: '小結',
    rankNum: 4,
    side: '西',
    stableId: 'arashio',
    birthplace: '福島県福島市',
    birthplaceCountry: '日本',
    birthdate: '1994-12-06',
    height: 182,
    weight: 130,
    debut: '2017年3月',
    debutRank: '前相撲',
    yusho: 1,
    sansho: { shukunsho: 3, kantosho: 1, ginosho: 4 },
    kinboshi: 1,
    favoriteKimarite: ['右四つ', '寄り切り', '突き落とし'],
    profile: '若元春の実弟。三兄弟力士の三男。前さばきの巧さが光る技巧派。2022年春場所で初優勝。'
  },

  // ===== 前頭 =====
  {
    id: 'takayasu',
    name: '高安',
    nameKana: 'たかやす',
    nameRomaji: 'Takayasu Akira',
    realName: '高安晃',
    rank: '前頭1',
    rankNum: 5,
    side: '東',
    stableId: 'tagonoura',
    birthplace: '茨城県土浦市',
    birthplaceCountry: '日本',
    birthdate: '1990-02-28',
    height: 187,
    weight: 175,
    debut: '2005年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 3, kantosho: 4, ginosho: 6 },
    kinboshi: 4,
    favoriteKimarite: ['右四つ', '寄り切り', '突き押し'],
    profile: 'フィリピン人の母を持つハーフ。元大関。優勝決定戦に何度も進むも未だ初優勝はならず。'
  },
  {
    id: 'asanoyama',
    name: '朝乃山',
    nameKana: 'あさのやま',
    nameRomaji: 'Asanoyama Hideki',
    realName: '石橋広暉',
    rank: '前頭1',
    rankNum: 5,
    side: '西',
    stableId: 'takasago',
    birthplace: '富山県富山市',
    birthplaceCountry: '日本',
    birthdate: '1994-03-01',
    height: 188,
    weight: 175,
    debut: '2016年3月',
    debutRank: '前相撲',
    yusho: 1,
    sansho: { shukunsho: 2, kantosho: 2, ginosho: 3 },
    kinboshi: 2,
    favoriteKimarite: ['右四つ', '寄り切り', '上手投げ'],
    profile: '元大関。2019年夏場所で平幕優勝。右四つからの寄りが強い。'
  },
  {
    id: 'mitakeumi',
    name: '御嶽海',
    nameKana: 'みたけうみ',
    nameRomaji: 'Mitakeumi Hisashi',
    realName: '大道久司',
    rank: '前頭2',
    rankNum: 5,
    side: '東',
    stableId: 'dewanoumi',
    birthplace: '長野県木曽郡上松町',
    birthplaceCountry: '日本',
    birthdate: '1992-12-25',
    height: 180,
    weight: 174,
    debut: '2015年3月',
    debutRank: '幕下10枚目格付出',
    yusho: 3,
    sansho: { shukunsho: 3, kantosho: 2, ginosho: 1 },
    kinboshi: 1,
    favoriteKimarite: ['突き押し', '寄り切り'],
    profile: '元大関。長野県出身。3度の幕内優勝経験を持つ。'
  },
  {
    id: 'tobizaru',
    name: '翔猿',
    nameKana: 'とびざる',
    nameRomaji: 'Tobizaru Masaya',
    realName: '吉田正也',
    rank: '前頭3',
    rankNum: 5,
    side: '東',
    stableId: 'oitekaze',
    birthplace: '東京都江戸川区',
    birthplaceCountry: '日本',
    birthdate: '1992-04-24',
    height: 175,
    weight: 132,
    debut: '2015年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 2, ginosho: 1 },
    kinboshi: 1,
    favoriteKimarite: ['押し出し', '叩き込み', '突き落とし'],
    profile: '小兵で動きが速い。多彩な技と俊敏さで観客を魅了。'
  },
  {
    id: 'ura',
    name: '宇良',
    nameKana: 'うら',
    nameRomaji: 'Ura Kazuki',
    realName: '宇良和輝',
    rank: '前頭3',
    rankNum: 5,
    side: '西',
    stableId: 'kise',
    birthplace: '大阪府寝屋川市',
    birthplaceCountry: '日本',
    birthdate: '1992-06-22',
    height: 175,
    weight: 145,
    debut: '2015年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 3, ginosho: 2 },
    kinboshi: 1,
    favoriteKimarite: ['居反り', '伝え反り', '送り出し'],
    profile: '関西学院大学出身。多彩な珍しい決まり手を繰り出す技巧派。怪我からの復活を果たした人気力士。'
  },
  {
    id: 'hiradoumi',
    name: '平戸海',
    nameKana: 'ひらどうみ',
    nameRomaji: 'Hiradoumi Yuto',
    realName: '田中雄大',
    rank: '前頭4',
    rankNum: 5,
    side: '東',
    stableId: 'sakaigawa',
    birthplace: '長崎県平戸市',
    birthplaceCountry: '日本',
    birthdate: '2000-04-20',
    height: 178,
    weight: 142,
    debut: '2016年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 1 },
    kinboshi: 1,
    favoriteKimarite: ['右四つ', '寄り切り', '突き落とし'],
    profile: '長崎県平戸市出身。若手有望株として注目される。'
  },
  {
    id: 'gonoyama',
    name: '豪ノ山',
    nameKana: 'ごうのやま',
    nameRomaji: 'Gonoyama Towa',
    realName: '武田登和',
    rank: '前頭4',
    rankNum: 5,
    side: '西',
    stableId: 'takadagawa',
    birthplace: '大阪府八尾市',
    birthplaceCountry: '日本',
    birthdate: '1998-08-30',
    height: 178,
    weight: 158,
    debut: '2021年3月',
    debutRank: '幕下15枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 1 },
    kinboshi: 0,
    favoriteKimarite: ['押し出し', '突き出し'],
    profile: '日本大学出身。鋭い突き押し相撲が持ち味。'
  },
  {
    id: 'midorifuji',
    name: '翠富士',
    nameKana: 'みどりふじ',
    nameRomaji: 'Midorifuji Kazuya',
    realName: '高木一也',
    rank: '前頭5',
    rankNum: 5,
    side: '東',
    stableId: 'isegahama',
    birthplace: '静岡県焼津市',
    birthplaceCountry: '日本',
    birthdate: '1996-09-19',
    height: 172,
    weight: 121,
    debut: '2015年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 1 },
    kinboshi: 1,
    favoriteKimarite: ['肩透かし', '突き落とし', '叩き込み'],
    profile: '小兵ながら肩透かしの名手として有名。'
  },
  {
    id: 'nishikifuji',
    name: '錦富士',
    nameKana: 'にしきふじ',
    nameRomaji: 'Nishikifuji Ryusei',
    realName: '杉野森龍盛',
    rank: '前頭5',
    rankNum: 5,
    side: '西',
    stableId: 'isegahama',
    birthplace: '青森県十和田市',
    birthplaceCountry: '日本',
    birthdate: '1996-07-22',
    height: 184,
    weight: 156,
    debut: '2015年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['右四つ', '寄り切り', '上手投げ'],
    profile: '青森県出身。鳥取城北高校から伊勢ヶ濱部屋へ。'
  },
  {
    id: 'ohho',
    name: '王鵬',
    nameKana: 'おうほう',
    nameRomaji: 'Ohho Konosuke',
    realName: '納谷幸之介',
    rank: '前頭6',
    rankNum: 5,
    side: '東',
    stableId: 'kokonoe',
    birthplace: '東京都江東区',
    birthplaceCountry: '日本',
    birthdate: '2000-02-14',
    height: 192,
    weight: 175,
    debut: '2018年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['突き押し', '寄り切り'],
    profile: '大横綱・大鵬の孫。次世代を担う期待の若手。'
  },
  {
    id: 'hokutofuji',
    name: '北勝富士',
    nameKana: 'ほくとふじ',
    nameRomaji: 'Hokutofuji Daiki',
    realName: '中村大輝',
    rank: '前頭6',
    rankNum: 5,
    side: '西',
    stableId: 'hakkaku',
    birthplace: '埼玉県所沢市',
    birthplaceCountry: '日本',
    birthdate: '1992-07-15',
    height: 183,
    weight: 165,
    debut: '2015年3月',
    debutRank: '幕下15枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 1 },
    kinboshi: 4,
    favoriteKimarite: ['押し出し', '突き出し'],
    profile: '日本大学出身。鋭い立ち合いと押し相撲が持ち味。'
  },
  {
    id: 'nishikigi',
    name: '錦木',
    nameKana: 'にしきぎ',
    nameRomaji: 'Nishikigi Tetsushi',
    realName: '熊谷哲也',
    rank: '前頭7',
    rankNum: 5,
    side: '東',
    stableId: 'isenoumi',
    birthplace: '岩手県盛岡市',
    birthplaceCountry: '日本',
    birthdate: '1990-08-25',
    height: 184,
    weight: 165,
    debut: '2005年9月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 0 },
    kinboshi: 2,
    favoriteKimarite: ['左四つ', '寄り切り', 'おっつけ'],
    profile: 'おっつけの名手。岩手県出身。'
  },
  {
    id: 'tamawashi',
    name: '玉鷲',
    nameKana: 'たまわし',
    nameRomaji: 'Tamawashi Ichiro',
    realName: 'マムベタル・バトジャルガル',
    rank: '前頭7',
    rankNum: 5,
    side: '西',
    stableId: 'kataonami',
    birthplace: 'モンゴル・ウランバートル',
    birthplaceCountry: 'モンゴル',
    birthdate: '1984-11-16',
    height: 189,
    weight: 175,
    debut: '2004年1月',
    debutRank: '前相撲',
    yusho: 2,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 4 },
    kinboshi: 3,
    favoriteKimarite: ['突き押し', '押し出し'],
    profile: '最年長クラスの幕内力士。怪我による休場のない鉄人として知られる。'
  },
  {
    id: 'endo',
    name: '遠藤',
    nameKana: 'えんどう',
    nameRomaji: 'Endo Shota',
    realName: '遠藤聖大',
    rank: '前頭8',
    rankNum: 5,
    side: '東',
    stableId: 'oitekaze',
    birthplace: '石川県穴水町',
    birthplaceCountry: '日本',
    birthdate: '1990-10-19',
    height: 184,
    weight: 152,
    debut: '2013年3月',
    debutRank: '幕下10枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 2, kantosho: 3, ginosho: 2 },
    kinboshi: 4,
    favoriteKimarite: ['右四つ', '寄り切り', '上手投げ'],
    profile: '日本大学出身。端正な顔立ちで人気の力士。技巧派の相撲。'
  },
  {
    id: 'takanosho',
    name: '隆の勝',
    nameKana: 'たかのしょう',
    nameRomaji: 'Takanosho Akihiro',
    realName: '石井伸明',
    rank: '前頭8',
    rankNum: 5,
    side: '西',
    stableId: 'tokiwayama',
    birthplace: '千葉県柏市',
    birthplaceCountry: '日本',
    birthdate: '1994-07-14',
    height: 184,
    weight: 175,
    debut: '2010年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 0 },
    kinboshi: 1,
    favoriteKimarite: ['押し出し', '突き出し'],
    profile: '常盤山部屋所属。鋭い突き押しが武器。'
  },
  {
    id: 'myogiryu',
    name: '妙義龍',
    nameKana: 'みょうぎりゅう',
    nameRomaji: 'Myogiryu Yasunari',
    realName: '宮本泰成',
    rank: '前頭9',
    rankNum: 5,
    side: '東',
    stableId: 'sakaigawa',
    birthplace: '兵庫県高砂市',
    birthplaceCountry: '日本',
    birthdate: '1986-10-22',
    height: 185,
    weight: 153,
    debut: '2009年5月',
    debutRank: '幕下10枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 4 },
    kinboshi: 4,
    favoriteKimarite: ['押し出し', '突き押し', 'おっつけ'],
    profile: '日本体育大学出身。テクニックある押し相撲が持ち味。'
  },
  {
    id: 'ichiyamamoto',
    name: '一山本',
    nameKana: 'いちやまもと',
    nameRomaji: 'Ichiyamamoto Daiki',
    realName: '山本大生',
    rank: '前頭9',
    rankNum: 5,
    side: '西',
    stableId: 'nishonoseki',
    birthplace: '北海道岩内町',
    birthplaceCountry: '日本',
    birthdate: '1993-10-12',
    height: 188,
    weight: 157,
    debut: '2017年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 0, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['突き押し', '突き出し'],
    profile: '北海道出身。鋭い突っ張りで上位を狙う。'
  },
  {
    id: 'shonannoumi',
    name: '湘南乃海',
    nameKana: 'しょうなんのうみ',
    nameRomaji: 'Shonannoumi Momotaro',
    realName: '熊谷桃太郎',
    rank: '前頭10',
    rankNum: 5,
    side: '東',
    stableId: 'takadagawa',
    birthplace: '神奈川県平塚市',
    birthplaceCountry: '日本',
    birthdate: '1997-06-13',
    height: 193,
    weight: 175,
    debut: '2013年5月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['右四つ', '寄り切り'],
    profile: '長身を活かした四つ相撲。神奈川県平塚市出身。'
  },
  {
    id: 'kinbozan',
    name: '金峰山',
    nameKana: 'きんぼうざん',
    nameRomaji: 'Kinbozan Haruki',
    realName: 'イェルシン・バルタゴル',
    rank: '前頭10',
    rankNum: 5,
    side: '西',
    stableId: 'kise',
    birthplace: 'カザフスタン・アルマトイ',
    birthplaceCountry: 'カザフスタン',
    birthdate: '1997-06-19',
    height: 191,
    weight: 175,
    debut: '2022年3月',
    debutRank: '幕下15枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['突き押し', '寄り切り'],
    profile: 'カザフスタン出身初の幕内力士。日本体育大学出身。'
  },
  {
    id: 'roga',
    name: '狼雅',
    nameKana: 'ろうが',
    nameRomaji: 'Roga Aleksandr',
    realName: 'アレクサンドル・エゴロフ',
    rank: '前頭11',
    rankNum: 5,
    side: '東',
    stableId: 'futagoyama',
    birthplace: 'ロシア・ブリヤート共和国',
    birthplaceCountry: 'ロシア',
    birthdate: '1998-10-08',
    height: 184,
    weight: 165,
    debut: '2018年5月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 0, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['右四つ', '寄り切り', '上手投げ'],
    profile: 'ロシア・ブリヤート共和国出身。'
  },
  {
    id: 'atamifuji',
    name: '熱海富士',
    nameKana: 'あたみふじ',
    nameRomaji: 'Atamifuji Sakutaro',
    realName: '武井朔太郎',
    rank: '前頭11',
    rankNum: 5,
    side: '西',
    stableId: 'isegahama',
    birthplace: '静岡県熱海市',
    birthplaceCountry: '日本',
    birthdate: '2002-09-03',
    height: 186,
    weight: 175,
    debut: '2020年11月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 0 },
    kinboshi: 1,
    favoriteKimarite: ['右四つ', '寄り切り'],
    profile: '熱海市出身の期待の若手。地元では絶大な人気を誇る。'
  },
  {
    id: 'chiyoshoma',
    name: '千代翔馬',
    nameKana: 'ちよしょうま',
    nameRomaji: 'Chiyoshoma Fujio',
    realName: 'ガナバータル・ムンフサイハン',
    rank: '前頭12',
    rankNum: 5,
    side: '東',
    stableId: 'kokonoe',
    birthplace: 'モンゴル・ウランバートル',
    birthplaceCountry: 'モンゴル',
    birthdate: '1991-07-20',
    height: 187,
    weight: 142,
    debut: '2009年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 0, ginosho: 0 },
    kinboshi: 1,
    favoriteKimarite: ['左四つ', '上手投げ', '突き落とし'],
    profile: '九重部屋所属。投げ技を得意とする。'
  },
  {
    id: 'sadanoumi',
    name: '佐田の海',
    nameKana: 'さだのうみ',
    nameRomaji: 'Sadanoumi Takashi',
    realName: '岩田貴洋',
    rank: '前頭12',
    rankNum: 5,
    side: '西',
    stableId: 'sakaigawa',
    birthplace: '熊本県熊本市',
    birthplaceCountry: '日本',
    birthdate: '1987-05-11',
    height: 182,
    weight: 134,
    debut: '2010年3月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 1 },
    kinboshi: 1,
    favoriteKimarite: ['押し出し', 'はたき込み'],
    profile: '同名の父も大相撲力士。熊本県出身。'
  },
  {
    id: 'tomokaze',
    name: '友風',
    nameKana: 'ともかぜ',
    nameRomaji: 'Tomokaze Yusuke',
    realName: '中村友哉',
    rank: '前頭13',
    rankNum: 5,
    side: '東',
    stableId: 'oitekaze',
    birthplace: '神奈川県川崎市',
    birthplaceCountry: '日本',
    birthdate: '1994-08-18',
    height: 186,
    weight: 167,
    debut: '2017年5月',
    debutRank: '幕下15枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 1, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['押し出し', '寄り切り'],
    profile: '日本大学出身。怪我から復活した苦労人。'
  },
  {
    id: 'hakuoho',
    name: '伯桜鵬',
    nameKana: 'はくおうほう',
    nameRomaji: 'Hakuoho Tetsuya',
    realName: '落合哲也',
    rank: '前頭13',
    rankNum: 5,
    side: '西',
    stableId: 'miyagino',
    birthplace: '鳥取県米子市',
    birthplaceCountry: '日本',
    birthdate: '2003-08-22',
    height: 182,
    weight: 160,
    debut: '2023年1月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 1, kantosho: 1, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['右四つ', '寄り切り', '上手投げ'],
    profile: '元横綱・白鵬の宮城野部屋出身。鳥取城北高校から角界入り。スピード出世した期待の星。'
  },
  {
    id: 'oshoma',
    name: '欧勝馬',
    nameKana: 'おうしょうま',
    nameRomaji: 'Oshoma Yuto',
    realName: 'ウラジオ・モンゴル',
    rank: '前頭14',
    rankNum: 5,
    side: '東',
    stableId: 'kise',
    birthplace: 'モンゴル・ウランバートル',
    birthplaceCountry: 'モンゴル',
    birthdate: '1997-06-23',
    height: 188,
    weight: 145,
    debut: '2022年9月',
    debutRank: '幕下15枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 0, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['右四つ', '寄り切り'],
    profile: '日本大学出身。モンゴル出身。'
  },
  {
    id: 'tokihayate',
    name: '時疾風',
    nameKana: 'ときはやて',
    nameRomaji: 'Tokihayate Genta',
    realName: '加藤拳太郎',
    rank: '前頭14',
    rankNum: 5,
    side: '西',
    stableId: 'tokitsukaze',
    birthplace: '愛知県豊川市',
    birthplaceCountry: '日本',
    birthdate: '1996-07-16',
    height: 184,
    weight: 145,
    debut: '2019年3月',
    debutRank: '幕下10枚目格付出',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 0, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['押し出し', '寄り切り'],
    profile: '中央大学出身。時津風部屋所属。'
  },
  {
    id: 'churanoumi',
    name: '美ノ海',
    nameKana: 'ちゅらのうみ',
    nameRomaji: 'Churanoumi Kenta',
    realName: '田中健太',
    rank: '前頭15',
    rankNum: 5,
    side: '東',
    stableId: 'kise',
    birthplace: '沖縄県うるま市',
    birthplaceCountry: '日本',
    birthdate: '1991-12-04',
    height: 178,
    weight: 142,
    debut: '2014年7月',
    debutRank: '前相撲',
    yusho: 0,
    sansho: { shukunsho: 0, kantosho: 0, ginosho: 0 },
    kinboshi: 0,
    favoriteKimarite: ['左四つ', '寄り切り'],
    profile: '沖縄県出身。木瀬部屋所属の中堅力士。'
  },
];

// 部屋を補完
STABLES.push(
  {
    id: 'isenoumi',
    name: '伊勢ノ海部屋',
    nameRomaji: 'Isenoumi-beya',
    ichimon: '時津風一門',
    location: '東京都墨田区両国',
    master: '伊勢ノ海親方（元前頭・北勝鬨）',
    established: '江戸時代',
    description: '相撲界最古級の部屋の一つ。錦木が看板力士。'
  },
  {
    id: 'kataonami',
    name: '片男波部屋',
    nameRomaji: 'Kataonami-beya',
    ichimon: '二所ノ関一門',
    location: '東京都墨田区石原',
    master: '片男波親方（元関脇・玉春日）',
    established: '1961年',
    description: '玉鷲、玉ノ井（玉鷲）など玉の四股名を継ぐ部屋。'
  },
  {
    id: 'tokiwayama',
    name: '常盤山部屋',
    nameRomaji: 'Tokiwayama-beya',
    ichimon: '出羽海一門',
    location: '東京都江東区東陽',
    master: '常盤山親方（元小結・隆三杉）',
    established: '2014年',
    description: '隆の勝などを抱える比較的新しい部屋。'
  },
  {
    id: 'miyagino',
    name: '宮城野部屋（伊勢ヶ濱部屋預かり）',
    nameRomaji: 'Miyagino-beya',
    ichimon: '伊勢ヶ濱一門',
    location: '東京都墨田区亀沢',
    master: '宮城野親方（元横綱・白鵬）→閉鎖中、伊勢ヶ濱部屋預かり',
    established: '1755年',
    description: '元横綱・白鵬が師匠を務めた伝統部屋。2024年に閉鎖となり、所属力士は伊勢ヶ濱部屋預かりに。'
  }
);

// ===== 場所結果（直近数場所）=====
const TOURNAMENTS = [
  {
    id: '2026-01',
    name: '令和8年 一月場所（初場所）',
    venue: '両国国技館',
    period: '2026年1月12日〜26日',
    yushoMakuuchi: { rikishiId: 'onosato', record: '14勝1敗', note: '4回目の優勝、横綱昇進を決める' },
    sansho: {
      shukunsho: ['daieisho'],
      kantosho: ['hakuoho'],
      ginosho: ['wakatakakage']
    },
    summary: '大の里が14勝1敗で優勝。場所後に横綱昇進が決定し、第75代横綱となる。'
  },
  {
    id: '2025-11',
    name: '令和7年 十一月場所（九州場所）',
    venue: '福岡国際センター',
    period: '2025年11月9日〜23日',
    yushoMakuuchi: { rikishiId: 'hoshoryu', record: '13勝2敗', note: '3回目の優勝' },
    sansho: {
      shukunsho: ['kotozakura'],
      kantosho: ['atamifuji'],
      ginosho: ['ura']
    },
    summary: '横綱・豊昇龍が13勝2敗で優勝。'
  },
  {
    id: '2025-09',
    name: '令和7年 九月場所（秋場所）',
    venue: '両国国技館',
    period: '2025年9月14日〜28日',
    yushoMakuuchi: { rikishiId: 'onosato', record: '13勝2敗', note: '3回目の優勝' },
    sansho: {
      shukunsho: ['wakatakakage'],
      kantosho: ['hiradoumi'],
      ginosho: ['kotozakura']
    },
    summary: '大関・大の里が13勝2敗で3度目の優勝。'
  },
  {
    id: '2025-07',
    name: '令和7年 七月場所（名古屋場所）',
    venue: '愛知県体育館（IGアリーナ）',
    period: '2025年7月13日〜27日',
    yushoMakuuchi: { rikishiId: 'kotozakura', record: '13勝2敗', note: '2回目の優勝' },
    sansho: {
      shukunsho: ['daieisho'],
      kantosho: ['hakuoho'],
      ginosho: ['ura']
    },
    summary: '大関・琴櫻が2度目の優勝。'
  },
  {
    id: '2025-05',
    name: '令和7年 五月場所（夏場所）',
    venue: '両国国技館',
    period: '2025年5月11日〜25日',
    yushoMakuuchi: { rikishiId: 'onosato', record: '14勝1敗', note: '2回目の優勝' },
    sansho: {
      shukunsho: ['wakatakakage'],
      kantosho: ['atamifuji'],
      ginosho: ['hakuoho']
    },
    summary: '大関・大の里が14勝1敗で2回目の優勝。'
  },
  {
    id: '2025-03',
    name: '令和7年 三月場所（春場所）',
    venue: 'エディオンアリーナ大阪',
    period: '2025年3月9日〜23日',
    yushoMakuuchi: { rikishiId: 'hoshoryu', record: '12勝3敗', note: '横綱昇進後の初場所' },
    sansho: {
      shukunsho: ['onosato'],
      kantosho: ['hiradoumi'],
      ginosho: ['midorifuji']
    },
    summary: '新横綱・豊昇龍が綱取りに成功した翌場所も優勝。'
  },
  {
    id: '2025-01',
    name: '令和7年 一月場所（初場所）',
    venue: '両国国技館',
    period: '2025年1月12日〜26日',
    yushoMakuuchi: { rikishiId: 'hoshoryu', record: '12勝3敗', note: '初優勝・横綱昇進決定' },
    sansho: {
      shukunsho: ['kinbozan'],
      kantosho: ['onosato'],
      ginosho: ['daieisho']
    },
    summary: '豊昇龍が初優勝、第74代横綱に昇進。'
  },
];

const ICHIMON_INFO = {
  '伊勢ヶ濱一門': '伊勢ヶ濱部屋を中心とした一門。',
  '時津風一門': '時津風部屋を中心とした一門。',
  '二所ノ関一門': '二所ノ関部屋を中心とした一門。多くの伝統ある部屋を含む。',
  '出羽海一門': '出羽海部屋を中心とした一門。最大級の歴史を持つ。',
  '高砂一門': '高砂部屋を中心とした一門。',
};

const RANK_ORDER = {
  '横綱': 1,
  '大関': 2,
  '関脇': 3,
  '小結': 4,
};

function getStableById(id) {
  return STABLES.find(s => s.id === id);
}

function getRikishiById(id) {
  return RIKISHI.find(r => r.id === id);
}

function getRikishiByStable(stableId) {
  return RIKISHI.filter(r => r.stableId === stableId);
}

function getStablesByIchimon(ichimon) {
  return STABLES.filter(s => s.ichimon === ichimon);
}

function rankSortValue(rikishi) {
  const baseRank = RANK_ORDER[rikishi.rank];
  if (baseRank) {
    return baseRank * 1000 + (rikishi.side === '東' ? 0 : 1);
  }
  // 前頭X
  const m = rikishi.rank.match(/前頭(\d+)/);
  if (m) {
    return 5000 + parseInt(m[1], 10) * 10 + (rikishi.side === '東' ? 0 : 1);
  }
  return 9999;
}

function sortByRank(list) {
  return [...list].sort((a, b) => rankSortValue(a) - rankSortValue(b));
}
